config/routes.rb
Superlist::Application.routes.draw do

  devise_for :users
  
  resources :todos, only: [:create, :destroy, :index] do
    collection do
        delete 'destroy_multiple'
      end
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  
  validates :body, length: { minimum: 5 }, presence: true

  default_scope { order('created_at ASC') }

  def days_left
    if self.created_at
      ((self.created_at + 8.days - Time.now).to_i)/60/60/24
    end
  end

  def self.delete_old_items
    Todo.where("created_at <= ?", Time.now - 7.days).destroy_all
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :todos, dependent: :destroy

end

app/controllers/Welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  after_action :flash_discard
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  def after_sign_in_path_for(resource)
    todos_path
  end

  def flash_discard
    # This will discontinue execution if Rails detects that the request is not
    # from an AJAX request, i.e. the header wont be added for normal requests
    return unless request.xhr?
   
    # Stops the flash appearing when you next refresh the page
    flash.discard
  end
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  respond_to :html, :js

  before_action :authenticate_user!
  
  def index
    @user = current_user
    @todos = @user.todos  
    @new_todo = Todo.new
    authorize @user
  end

  def create
    @todo = current_user.todos.build(todo_params)
    @new_todo = current_user.todos.build
    authorize @todo


    if @todo.save
      flash[:notice] = "Todo was saved."
    else
      flash[:error] = "There was an error saving the todo item. Please try again."
    end

    respond_with(@todo) do |format|
      format.html { redirect_to todos_path }
    end

  end

  def destroy
    @todo = current_user.todos.find(params[:id])
    authorize @todo

    if @todo.destroy
      flash[:notice] = "Todo item was removed."
    else
      flash[:error] = "Todo item couldn't be deleted. Try again."
    end

    respond_with(@todo) do |format|
      format.html { redirect_to todos_path }
    end

   end

  def destroy_multiple

    ids = params[:todos]
    
    if ids.present?
      if current_user.todos.where(id: ids).destroy_all
        flash[:notice] = "Completed todo items were removed."
        redirect_to todos_path
      else
        flash[:error] = "Completed todo items couldn't be deleted. Try again."
        redirect_to todos_path
      end
    else
      flash[:error] = "Please make sure to mark the completed todo item"
      redirect_to todos_path
    end

  end

  private

  def todo_params
    params.require(:todo).permit(:body)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/welcome_controller_temp.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button tye="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:error] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superlist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Superlist", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <% if current_user %>
      <li><%= link_to "My List", todos_path %></li>
    <% end %>
    <div class="pull-right user-info">
      <% if current_user %>
        Hello <b><%= current_user.name || current_user.email %></b>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> or 
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
    
  </ul>

  <div class="flash">
    <%= render partial: 'layouts/flash' %>
  </div>

  <%= yield %>
</div>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for todo, remote: true do |f| %>

  <div class="form-group">
    <%= f.label :body, 'Todo Item' %>
    <%= f.text_area :body, rows: 4, class: 'form-control', placeholder: "Enter todo item" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create", class: 'btn btn-success' %>
  </div>
  
<% end %>

app/views/todos/_todo.html.erb
<%= content_tag :tbody, class: 'tbody', id: "todo-#{todo.id}" do %>
  <tr>

      <td><%= todo.body %></td>
      <td><%= todo.days_left %></td>
      <td><input id="todo_<%=todo.id %>" name="todos[]" value="<%=todo.id %>"  type= "checkbox"  /></td>
      <td><%= link_to "Delete", todo, method: :delete, remote: true, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this todo item?' } %></td>
 
  </tr>
<% end %>

app/views/todos/create.js.erb
<% if @todo.valid? %>
  $('.js-todos').append("<%= escape_javascript(render(@todo)) %>");
  $('.new-todo').html("<%= escape_javascript(render partial: 'todos/form', locals: { user: @todo.user, todo: @new_todo }) %>");
  $('.flash').after("<%= escape_javascript(render partial: 'layouts/flash') %>");
<% else %>
  $('.flash').after("<%= escape_javascript(render partial: 'layouts/flash') %>");
<% end %>

app/views/todos/destroy.js.erb
<% if @todo.destroyed? %>
  $('#todo-' + <%= @todo.id %>).fadeOut(600);
  $('.flash').after("<%= escape_javascript(render partial: 'layouts/flash') %>");
<% else %>
  $('.flash').after("<%= escape_javascript(render partial: 'layouts/flash') %>");
<% end %>

app/views/todos/index.html.erb
<div class="row">
  <div class ="col-md-2">
  </div>
  <div class="col-md-8 center">
  <h1>Superlist - Todo!</h1><br/>
  <%= form_tag destroy_multiple_todos_path, method: :delete do %>
  <table class="table js-todos table-striped">
    <thead>
      <tr>
        <th>Todo list</th>
        <th>Days left</th>
        <th>Completed</th>
        <th>Action</th>
      </tr>
    </thead>
    
      <%= render partial: 'todos/todo', collection: @todos %>
    
  </table>
  <%= submit_tag "Delete completed" %>
  <% end %>
    
    
    <br/>
    <div class='new-todo'>
      <%= render partial: 'todos/form', locals: { user: @user, todo: @new_todo} %>
    </div>
  </div>

  <div class ="col-md-2">
  </div>

</div>

app/views/welcome/about.html.erb
<h1>About Superlist</h1>
<p>Created by: Jaya </p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Superlist</h1>
  <p>SuperList - A self-destructing to-do list to keep you focused on the things that really matter!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>

</div>
 
<div class="row">
  <div class="col-md-4">
    <h2>Solves your problems</h2>
    <p>Superlist will help you tackle your problems.</p>
  </div>
  <div class="col-md-4">
    <h2>Solve problems with friends!</h2>
    <p>Superlist will help you share your Todos with friends and solve problems together!.</p>
  </div>
  <div class="col-md-4">
    <h2>Easier grocerry shopping </h2>
    <p>Superlist will make your life easier with your grocery shopping.</p>
  </div>
</div> 